from . import pharmacy_catalog
from . import product_template
from . import res_partner
from . import pharmacy_supplier
from . import pharmacy_supplier_return
from . import pharmacy_return
from . import pharmacy_wholesale
from . import pharmacy_clinical
from . import pharmacy_prescription
from . import pharmacy_dispense
from . import pharmacy_controlled
from . import stock_lot
from . import sale_pos_guard
from . import pharmacy_expiry_control
from . import pos_pharmacy
from . import pharmacy_compliance
from . import pharmacy_insurance
from . import pharmacy_stock_intelligence
from . import pharmacy_dashboard
from . import pharmacy_reporting
from . import res_config_settings
